"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import os
from setuptools import setup

APP = ['main.py']

# sounds/ 디렉토리 내 모든 wav 파일 포함
sounds_files = [
    os.path.join('sounds', f)
    for f in os.listdir('sounds')
    if f.endswith('.wav')
]

DATA_FILES = [
    ('', ['config.json', 'pose_landmarker_lite.task']),
    ('sounds', sounds_files),
]
OPTIONS = {
    'no_zip': True,
    'packages': ['PySide6', 'psutil', 'cv2', 'mediapipe', 'numpy'],
    'includes': [
        'main_window', 'config', 'process_monitor',
        'aim_game', 'bug_game', 'keyboard_game', 'motion_game', 'sounds',
    ],
}

setup(
    name='AimGuard',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
