"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import os
from setuptools import setup

APP = ['main.py']

# sounds/ 디렉토리 내 모든 wav 파일 포함
sounds_files = [
    os.path.join('sounds', f)
    for f in os.listdir('sounds')
    if f.endswith('.wav')
]

DATA_FILES = [
    ('', ['config.json', 'pose_landmarker_lite.task']),
    ('sounds', sounds_files),
]
OPTIONS = {
    'no_zip': True,
    'plist': {
        'NSMicrophoneUsageDescription': 'AimGuard가 소리 데시벨 게임에 마이크를 사용합니다.',
        'NSCameraUsageDescription': 'AimGuard가 모션 게임(스쿼트/푸시업)에 카메라를 사용합니다.',
    },
    'packages': ['PySide6', 'psutil', 'cv2', 'mediapipe', 'numpy', '_sounddevice_data'],
    'includes': [
        'main_window', 'config', 'process_monitor',
        'aim_game', 'bug_game', 'keyboard_game', 'motion_game', 'audio_game', 'sounds',
        'sounddevice', '_sounddevice',
        'camera_permission',
    ],
    'excludes': [
        'PyQt5', 'PyQt6',
        'matplotlib', 'mpl_toolkits',
        'pygments',
        'setuptools', 'pkg_resources', 'distutils',
        'tkinter', '_tkinter', 'Tkinter',
        'unittest', 'doctest', 'pydoc',
        'IPython', 'ipython', 'ipykernel',
        'scipy',
        'pandas',
        'PIL', 'Pillow',
        'wx', 'gi', 'gtk',
        'PyInstaller',
        'cffi',
    ],
    'strip': True,
    'optimize': 1,
}

setup(
    name='AimGuard',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
