"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = []
OPTIONS = {
    'no_zip': True,
    'frameworks': ['/Users/hj/miniconda3/lib/libffi.8.dylib'],
}

setup(
    name='AimGuard',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
